Webapp/Models/ErrorViewModel.cs
using System;

namespace EZAZ.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Webapp/Models/users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EZAZ.Models
{
    public class users
    {
        public int ID  { get; set; }
        public string username { get; set; }
        public int score { get; set; }
        public bool ban { get; set; }

        public users()
        {

        }
    }
}

Webapp/Models/words.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EZAZ.Models
{
    public class words
    {
        public int ID { get; set; }
        public string word { get; set; }
        public int score { get; set; }

        public words()
        {

        }

    }
}

Webapp/Controllers/HomeController.cs
using EZAZ.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EZAZ.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Webapp/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EZAZ.Data;
using EZAZ.Models;
using Microsoft.AspNetCore.Authorization;

namespace EZAZ.Controllers
{
    public class usersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public usersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: users
        public async Task<IActionResult> Index()
        {
            return View(await _context.users.ToListAsync());
        }

        // Submit: users/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        //Submit: users/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index", await _context.users.Where(j => j.username.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.users
                .FirstOrDefaultAsync(m => m.ID == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }
        
        

        private bool usersExists(int id)
        {
            return _context.users.Any(e => e.ID == id);
        }
    }
}

Webapp/Controllers/wordsController.cs
using EZAZ.Data;
using EZAZ.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace EZAZ.Controllers
{
    public class wordsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public wordsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: words
        public async Task<IActionResult> Index()
        {
            return View(await _context.words.ToListAsync());
        }

        //GET: words/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        //Submit: words/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index",await _context.words.Where (j => j.word.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: words/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var words = await _context.words
                .FirstOrDefaultAsync(m => m.ID == id);
            if (words == null)
            {
                return NotFound();
            }

            return View(words);
        }

        // GET: words/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: words/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,word,score")] words words)
        {
            if (ModelState.IsValid)
            {
                _context.Add(words);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(words);
        }

        // GET: words/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var words = await _context.words.FindAsync(id);
            if (words == null)
            {
                return NotFound();
            }
            return View(words);
        }

        // POST: words/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,word,score")] words words)
        {
            if (id != words.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(words);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!wordsExists(words.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(words);
        }

        // GET: words/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var words = await _context.words
                .FirstOrDefaultAsync(m => m.ID == id);
            if (words == null)
            {
                return NotFound();
            }

            return View(words);
        }

        // POST: words/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var words = await _context.words.FindAsync(id);
            _context.words.Remove(words);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool wordsExists(int id)
        {
            return _context.words.Any(e => e.ID == id);
        }
    }
}

Webapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Főoldal";
}


<!--<div class="conatiner">
    
    <div class="menu-btn">
        <i class="fas fa-bars"></i>
    </div>

    <div class="Navbar">
        <div class="close-btn">
            <i class="fas fa-times"></i>
        </div>

        <div class="Menu">
            <div class="item"><a href="signup.html"><i class="fa fa-sign-in"></i>Regisztráció</a></div>


            <div class="item"><a href="login.html"><i class="fa fa-user"></i>Bejelntkezés</a></div>


            <div class="item">
                <a class="leiras-btn"><i class="fa fa-info"></i>Leírás<i class="fa fa-angle-right dropdown"></i></a>
                <div class="leiras-menu">
                    <a href="#" class="munka">Rólunk</a>
                    <a href="leiras.html" class="munka">A játékról</a>
                </div>
            </div>
        </div>
    </div>

</div>-->



<section class="szoveg">
    <h1>Akasztó fa<br>projektmunka</h1>
</section>
<div class="alairas">

</div>

<!-- <script type="text/javascript">
     $(document).ready(function(){
         //jquery for menus
         $('.leiras-btn').click(function(){
             $(this).next('.leiras-menu').slideToggle();
             $(this).find('dropdown').toggleClass('rotate');
         });

         //jquaery for expand and collapse the sidebar
         $('.menu-btn').click(function(){
             $('.Navbar').addClass('active');
             $('.menu-btn').css("visibility", "hidden");
         });
         $('.close-btn').click(function(){
             $('.Navbar').removeClass('active');
             $('.menu-btn').css("visibility", "visible");
         });
     });
 </script>-->
<footer>Készítették:Nyíri Zsombor, Juhász Bence, Tóth Patrik </footer>

Webapp/Views/Home/leiras.cshtml
@{
    ViewData["Title"] = "Leírás";
  }
<h1>@ViewData["Title"]</h1>


<h1>Leírás</h1>
<p>Ezt a játkot azért készítettük mert...</p>

Webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projekt</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Főoldal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="users" asp-action="Index">Játékosok</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="words" asp-action="Index">Szavak</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="words" asp-action="ShowSearchForm">Szókereső</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="users" asp-action="ShowSearchForm">Játékos kereső</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EZAZ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Webapp/Views/users/Create.cshtml
@model EZAZ.Models.users

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="username" class="control-label"></label>
                <input asp-for="username" class="form-control" />
                <span asp-validation-for="username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="score" class="control-label"></label>
                <input asp-for="score" class="form-control" />
                <span asp-validation-for="score" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ban" /> @Html.DisplayNameFor(model => model.ban)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webapp/Views/users/Delete.cshtml
@model EZAZ.Models.users

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>users</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.score)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ban)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ban)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Webapp/Views/users/Details.cshtml
@model EZAZ.Models.users

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>users</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.score)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ban)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ban)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Webapp/Views/users/Edit.cshtml
@model EZAZ.Models.users

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="username" class="control-label"></label>
                <input asp-for="username" class="form-control" />
                <span asp-validation-for="username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="score" class="control-label"></label>
                <input asp-for="score" class="form-control" />
                <span asp-validation-for="score" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ban" /> @Html.DisplayNameFor(model => model.ban)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webapp/Views/users/Index.cshtml
@model IEnumerable<EZAZ.Models.users>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.score)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ban)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ban)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Webapp/Views/users/ShowSearchForm.cshtml
<h4>Játékos kereső</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">                       
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />                
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Webapp/Views/words/Create.cshtml
@model EZAZ.Models.words

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>words</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="word" class="control-label"></label>
                <input asp-for="word" class="form-control" />
                <span asp-validation-for="word" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="score" class="control-label"></label>
                <input asp-for="score" class="form-control" />
                <span asp-validation-for="score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webapp/Views/words/Delete.cshtml
@model EZAZ.Models.words

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>words</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.word)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.word)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.score)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Webapp/Views/words/Details.cshtml
@model EZAZ.Models.words

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>words</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.word)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.word)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.score)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Webapp/Views/words/Edit.cshtml
@model EZAZ.Models.words

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>words</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="word" class="control-label"></label>
                <input asp-for="word" class="form-control" />
                <span asp-validation-for="word" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="score" class="control-label"></label>
                <input asp-for="score" class="form-control" />
                <span asp-validation-for="score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webapp/Views/words/Index.cshtml
@model IEnumerable<EZAZ.Models.words>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.word)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.score)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.word)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.score)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Webapp/Views/words/ShowSearchForm.cshtml
<h4>Szókereső</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">                    
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>